site_name: PowerForensics
repo_url: https://github.com/Invoke-IR/PowerForensics
site_favicon: favicon.ico
pages:
- Home: 'index.md'
- PowerShell Module:
    - Installation: moduleinstall.md
    - Cmdlets:
        - Copy-ForensicFile: Module/Copy-ForensicFile.md
        - Get-ForensicAlternateDataStream: Module/Get-ForensicAlternateDataStream.md
        - Get-ForensicAmcache: Module/Get-ForensicAmcache.md
        - Get-ForensicAttrDef: Module/Get-ForensicAttrDef.md
        - Get-ForensicBitmap: Module/Get-ForensicBitmap.md
        - Get-ForensicBootSector: Module/Get-ForensicBootSector.md
        - Get-ForensicChildItem: Module/Get-ForensicChildItem.md
        - Get-ForensicContent: Module/Get-ForensicContent.md
        - Get-ForensicEventLog: Module/Get-ForensicEventLog.md
        - Get-ForensicExplorerTypedPath: Module/Get-ForensicExplorerTypedPath.md
        - Get-ForensicFileRecord: Module/Get-ForensicFileRecord.md
        - Get-ForensicFileRecordIndex: Module/Get-ForensicFileRecordIndex.md
        - Get-ForensicFileSlack: Module/Get-ForensicFileSlack.md
        - Get-ForensicGuidPartitionTable: Module/Get-ForensicGuidPartitionTable.md
        - Get-ForensicMasterBootRecord: Module/Get-ForensicMasterBootRecord.md
        - Get-ForensicMftSlack: Module/Get-ForensicMftSlack.md
        - Get-ForensicNetworkList: Module/Get-ForensicNetworkList.md
        - Get-ForensicOfficeFileMru: Module/Get-ForensicOfficeFileMru.md
        - Get-ForensicOfficeOutlookCatalog: Module/Get-ForensicOfficeOutlookCatalog.md
        - Get-ForensicOfficeTrustRecord: Module/Get-ForensicOfficeTrustRecord.md
        - Get-ForensicPartitionTable: Module/Get-ForensicPartitionTable.md
        - Get-ForensicPrefetch: Module/Get-ForensicPrefetch.md
        - Get-ForensicRecentFileCache: Module/Get-ForensicRecentFileCache.md
        - Get-ForensicRegistryKey: Module/Get-ForensicRegistryKey.md
        - Get-ForensicRegistryValue: Module/Get-ForensicRegistryValue.md
        - Get-ForensicRunKey: Module/Get-ForensicRunKey.md
        - Get-ForensicRunMru: Module/Get-ForensicRunMru.md
        - Get-ForensicScheduledJob: Module/Get-ForensicScheduledJob.md
        - Get-ForensicShellLink: Module/Get-ForensicShellLink.md
        - Get-ForensicShimcache: Module/Get-ForensicShimcache.md
        - Get-ForensicSid: Module/Get-ForensicSid.md
        - Get-ForensicTimeline: Module/Get-ForensicTimeline.md
        - Get-ForensicTimezone: Module/Get-ForensicTimezone.md
        - Get-ForensicTypedUrl: Module/Get-ForensicTypedUrl.md
        - Get-ForensicUnallocatedSpace: Module/Get-ForensicUnallocatedSpace.md
        - Get-ForensicUserAssist: Module/Get-ForensicUserAssist.md
        - Get-ForensicUsnJnrl: Module/Get-ForensicUsnJrnl.md
        - Get-ForensicUsnJnrlInformation: Module/Get-ForensicUsnJrnlInformation.md
        - Get-ForensicVolumeBootRecord: Module/Get-ForensicVolumeBootRecord.md
        - Get-ForensicVolumeInformation: Module/Get-ForensicVolumeInformation.md
        - Get-ForensicVolumeName: Module/Get-ForensicVolumeName.md
        - Get-ForensicWindowsSearchHistory: Module/Get-ForensicWindowsSearchHistory.md
        - Invoke-ForensicDD: Module/Invoke-ForensicDD.md
- Development:
    - .NET Library: library.md
- About:
    - License: '../LICENSE.md'